/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.JOptionPane;

/**
 *
 * @author Rudi Erwanto
 */
public class Konversi extends javax.swing.JFrame {

    /**
     * Creates new form Konversi
     */
    public Konversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Biner = new javax.swing.JTextField();
        Desimal = new javax.swing.JTextField();
        Convert = new javax.swing.JButton();
        Type = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KUY?!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("KONVERSI BILANGAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 60, 394, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Bilangan Desimal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 180, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Bilangan Biner");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 310, 190, 30);

        Biner.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(Biner);
        Biner.setBounds(330, 300, 280, 40);

        Desimal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(Desimal);
        Desimal.setBounds(330, 180, 280, 40);

        Convert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Convert.setText("Convert ");
        Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertActionPerformed(evt);
            }
        });
        getContentPane().add(Convert);
        Convert.setBounds(350, 390, 220, 31);

        Type.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Type.setText("=>");
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Type);
        Type.setBounds(420, 250, 53, 31);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(709, 492, 41, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 640);

        setSize(new java.awt.Dimension(912, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertActionPerformed
      try{
          if(Biner.getText().isEmpty()){
              int Desi = Integer.valueOf(Desimal.getText());
              String Bin = Integer.toBinaryString(Desi);
              Biner.setText(Bin);
          }else{
              String biner = Biner.getText();
              int desi = Integer.parseInt(biner, 2);
              Desimal.setText(Integer.toUnsignedString(desi));
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Input tidak valid : " +e.getMessage());
      }finally{
          Biner.setEnabled(true);
          Desimal.setEnabled(true);
      }
    }//GEN-LAST:event_ConvertActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
      if(Type.getText().equals("=>")){
          Type.setText("<=");
      }else{
          Type.setText("=>");
      }
      if(Type.getText().equals("=>")){
          Biner.setEnabled(false);
          Biner.setText("");
          Desimal.setEnabled(true);
      }else{
          Biner.setEnabled(true);
          Desimal.setEnabled(false);
          Desimal.setText("");
      }
    }//GEN-LAST:event_TypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Biner;
    private javax.swing.JButton Convert;
    private javax.swing.JTextField Desimal;
    private javax.swing.JButton Type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
