/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

/**
 *
 * @author Rudi Erwanto
 */
public class Latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox4 = new javax.swing.JCheckBox();
        Choice = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ABSEN = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        rdbTKJ = new javax.swing.JRadioButton();
        rdbRPL = new javax.swing.JRadioButton();
        cbVideoEditing = new javax.swing.JCheckBox();
        cbProgamming = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbDesigner = new javax.swing.JCheckBox();
        Exit = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HASIL = new javax.swing.JTextArea();

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox4.setText("Designer");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 30, 230, 110);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("ABSEN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 250, 70, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("JURUSAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 310, 90, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("HOBBY");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 370, 70, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("NAMA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 180, 70, 30);

        ABSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABSENActionPerformed(evt);
            }
        });
        getContentPane().add(ABSEN);
        ABSEN.setBounds(240, 240, 300, 40);

        NAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMAActionPerformed(evt);
            }
        });
        getContentPane().add(NAMA);
        NAMA.setBounds(240, 180, 300, 40);

        Choice.add(rdbTKJ);
        rdbTKJ.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rdbTKJ.setText("TKJ");
        rdbTKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTKJActionPerformed(evt);
            }
        });
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(240, 310, 53, 25);

        Choice.add(rdbRPL);
        rdbRPL.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rdbRPL.setText("RPL");
        getContentPane().add(rdbRPL);
        rdbRPL.setBounds(430, 310, 107, 25);

        cbVideoEditing.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbVideoEditing.setText("Video Editing");
        cbVideoEditing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVideoEditingActionPerformed(evt);
            }
        });
        getContentPane().add(cbVideoEditing);
        cbVideoEditing.setBounds(430, 430, 130, 25);

        cbProgamming.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbProgamming.setText("Progamming");
        cbProgamming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProgammingActionPerformed(evt);
            }
        });
        getContentPane().add(cbProgamming);
        cbProgamming.setBounds(240, 380, 120, 25);

        cbAnimator.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbAnimator.setText("Animator");
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(430, 380, 120, 25);

        cbDesigner.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbDesigner.setText("Designer");
        getContentPane().add(cbDesigner);
        cbDesigner.setBounds(240, 430, 120, 25);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(500, 500, 79, 25);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(130, 500, 73, 25);

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        getContentPane().add(Remove);
        Remove.setBounds(370, 500, 79, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("HASIL");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 550, 70, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan/noob.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(670, 20, 230, 230);

        HASIL.setColumns(20);
        HASIL.setRows(5);
        jScrollPane1.setViewportView(HASIL);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(156, 590, 410, 110);

        setSize(new java.awt.Dimension(962, 769));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ABSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABSENActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABSENActionPerformed

    private void NAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMAActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NAMAActionPerformed

    private void rdbTKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTKJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbTKJActionPerformed

    private void cbVideoEditingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVideoEditingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVideoEditingActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        // TODO add your handling code here:
        NAMA.setText(" ");
        ABSEN.setText(" ");
        Choice.clearSelection();
        HASIL.setText(" ");
        cbProgamming.setSelected(false);
        cbAnimator.setSelected(false);
        cbDesigner.setSelected(false);
        cbVideoEditing.setSelected(false);
        
    }//GEN-LAST:event_RemoveActionPerformed

    private void cbProgammingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgammingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgammingActionPerformed
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String nama = NAMA.getText();
        String absen = ABSEN.getText();
        String jurusan;
        String hobby ="";
        
        if(rdbRPL.isSelected())
            jurusan = "RPL";
        else if(rdbTKJ.isSelected())
            jurusan = "TKJ";
        else
            jurusan = " ";
        
        if(cbAnimator.isSelected())
            hobby +=cbAnimator.getText()+", ";
        if(cbDesigner.isSelected())
            hobby +=cbDesigner.getText()+", ";
        if(cbProgamming.isSelected())
            hobby +=cbProgamming.getText()+", ";
        if(cbVideoEditing.isSelected())
            hobby +=cbVideoEditing.getText()+"  ";
        
        HASIL.setText("Nama Anda = "+nama+"\n Absen Anda = "+absen+"\n Jurusan Anda = "+jurusan+"\n Hobby Anda = "+hobby);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ABSEN;
    private javax.swing.ButtonGroup Choice;
    private javax.swing.JButton Exit;
    private javax.swing.JTextArea HASIL;
    private javax.swing.JTextField NAMA;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Submit;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesigner;
    private javax.swing.JCheckBox cbProgamming;
    private javax.swing.JCheckBox cbVideoEditing;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    // End of variables declaration//GEN-END:variables
}
