/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Rudi Erwanto
 */
public class Latihan3ModulLanjutan extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3ModulLanjutan
     */
    public Latihan3ModulLanjutan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hitung = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Hitung2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        Hitung3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VOLUME ");
        setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Program Pencari Voulme Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 625, 40);

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));
        jPanel4.setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(670, 600, 90, 40);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Masukkan Panjang  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 40, 230, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 220, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Masukkan Tinggi    :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 180, 220, 30);

        Lebar.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(Lebar);
        Lebar.setBounds(260, 110, 140, 30);

        Tinggi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(Tinggi);
        Tinggi.setBounds(260, 180, 140, 30);

        Panjang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel1.add(Panjang);
        Panjang.setBounds(260, 40, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 180, 41, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 40, 30, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(420, 110, 41, 30);

        Hitung.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Hitung.setText("HITUNG!!");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });
        jPanel1.add(Hitung);
        Hitung.setBounds(230, 250, 141, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan/gambar-balok.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(380, 240, 358, 220);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(22, 44, 250, 30);

        Sisi.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel2.add(Sisi);
        Sisi.setBounds(19, 90, 240, 34);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(290, 90, 40, 30);

        Hitung2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Hitung2.setText("HITUNG!!");
        Hitung2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitung2ActionPerformed(evt);
            }
        });
        jPanel2.add(Hitung2);
        Hitung2.setBounds(70, 140, 141, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan/Kubus.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(340, 40, 400, 370);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Masukkan Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(40, 50, 220, 30);

        Jari.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jPanel3.add(Jari);
        Jari.setBounds(40, 92, 160, 30);

        Hitung3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Hitung3.setText("HITUNG!!");
        Hitung3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hitung3ActionPerformed(evt);
            }
        });
        jPanel3.add(Hitung3);
        Hitung3.setBounds(90, 140, 141, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(220, 90, 40, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Latihan/bola.jpg"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(360, 30, 225, 230);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel4.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 90, 750, 500);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Balok");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("Balok");

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 770, 650);

        setSize(new java.awt.Dimension(793, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
       int panjang,lebar,tinggi;
       panjang = Integer.parseInt(Panjang.getText());
       lebar = Integer.parseInt(Lebar.getText());
       tinggi = Integer.parseInt(Tinggi.getText());
       int hasil = panjang * lebar * tinggi;
       try{
           JOptionPane.showMessageDialog(null,"Volume Balok adalah : " +hasil+ "cm","title",JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error : " +e, "Gagal",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_HitungActionPerformed

    private void Hitung2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hitung2ActionPerformed
      int sisi;
      sisi = Integer.parseInt(Sisi.getText());
      int hasil = sisi * sisi * sisi;
      try{
          JOptionPane.showMessageDialog(null,"Volume Kubus Adalah : " +hasil+ "cm","tittle",JOptionPane.INFORMATION_MESSAGE);
      }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error : " +e, "Gagal",JOptionPane.WARNING_MESSAGE);    
      }
      
    }//GEN-LAST:event_Hitung2ActionPerformed

    private void Hitung3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hitung3ActionPerformed
       float jari;
       jari = Integer.parseInt(Jari.getText());
       float hasil = (float) (4/3 * 3.14 * jari*jari);
       try{
           JOptionPane.showMessageDialog(null,"Volume Bola Adalah : " +hasil+ "cm","tittle",JOptionPane.INFORMATION_MESSAGE);
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Error : " +e, "Gagal",JOptionPane.WARNING_MESSAGE);    
       }
    }//GEN-LAST:event_Hitung3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3ModulLanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3ModulLanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3ModulLanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3ModulLanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3ModulLanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JButton Hitung2;
    private javax.swing.JButton Hitung3;
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
